/** Homepage raster assets — export from Figma at 0 radius; clip via CSS `rounded-radius-*`. */

export const assets = {
  logo: "/seltaris-full-logo.svg",
  heroBackground: "/images/home/hero-background.png",
  whatIsImage: "/images/home/laptop.png",
  servicesHero: "/images/home/services-hero.png",
  humanTouchShowcase: "/images/home/human-touch-showcase.png",
  humanTouchSide: "/images/home/human-touch-side.png",
  humanTouch1: "/images/home/human-touch-1.png",
  humanTouch2: "/images/home/human-touch-2.png",
  humanTouch3: "/images/home/human-touch-3.png",
  humanTouchQuality1: "/images/home/human-touch-quality-1.png",
  humanTouchQuality2: "/images/home/human-touch-quality-2.png",
  humanTouchQuality3: "/images/home/human-touch-quality-3.png",
  humanTouchUnverified1: "/images/home/human-touch-unverified-1.png",
  humanTouchUnverified2: "/images/home/human-touch-unverified-2.png",
  altraserviceHero: "/images/home/altraservice-hero.png",
  altraserviceSide: "/images/home/altraservice-side.png",
  altraservice1: "/images/home/altraservice-1.png",
  altraservice2: "/images/home/altraservice-2.png",
  altraservice3: "/images/home/altraservice-3.png",
  platformShowcase: "/images/home/platform-showcase.png",
  securitySide: "/images/home/security-side.png",
  security1: "/images/home/security-1.png",
  security2: "/images/home/security-2.png",
  security3: "/images/home/security-3.png",
  workflowShowcase: "/images/home/workflow-showcase.png",
  healthSide: "/images/home/health-side.png",
  health1: "/images/home/health-1.png",
  health2: "/images/home/health-2.png",
  health3: "/images/home/health-3.png",
  chevronDown: "/icons/chevron.svg",
  arrowUp: "/icons/arrow.svg",
  learnMoreArrow: "/images/home/learn-more-arrow.png",
  sliderButton: "/icons/slider-button.svg",
  checkIcon: "/icons/check-icon.svg",
  checkIconAlt: "/images/home/check-icon-alt.png",
  pricingIcons: {
    repaired: "/images/home/pricing-icon-repaired.png",
    health: "/images/home/pricing-icon-health.png",
    subscription: "/seltaris-logo.svg",
  },
  trustedLogos: [
    "/images/company-icons/boq-logo-6511cbd6c366f.webp",
    "/images/company-icons/leukaemia-foundation-logo-6511cbd8dbed6.webp",
    "/images/company-icons/apra-amcos-logo-6511cbd57b7db.webp",
    "/images/company-icons/hcf-logo-6511cbd81b4b0.webp",
    "/images/company-icons/rabobank-logo-6511cbda23b00.webp",
    "/images/company-icons/commonwealth_bank.webp",
    "/images/company-icons/crown-logo-1.png",
    "/images/company-icons/qantas.webp",
    "/images/company-icons/guide-dogs-logo-6511cbd81b4ba.webp",
    "/images/company-icons/seafolly-australia-logo-6511cbdb7ed7b.webp",
    "/images/company-icons/nimble-logo-6511cbd985177.webp",
    "/images/company-icons/david-jones-logo-6511cbd775386.webp",
    "/images/company-icons/boc-logo-6511cbd649388.webp",
    "/images/company-icons/specasvers-logo-6511cbdc32c67.webp",
    "/images/company-icons/bible-society-logo-6511cbd631f29.webp",
    "/images/company-icons/unsw-logo-6511cbdcc724c.webp",
    "/images/company-icons/huntry-jacks-logo-6511cbd8d79b4.webp",
    "/images/company-icons/redballoon-logo-6511cbdac4ed7.webp",
    "/images/company-icons/catholic-mission-logo-6511cbd6decc4.webp",
    "/images/company-icons/uniqlo-1-2048x584.webp",
    "/images/company-icons/rmwilliams.png",
    "/images/company-icons/rodd-and-gunn-logo-6511cbdac4eb9.webp",
  ],
  serviceIcons: {
    address: "/images/home/service-icon-address.png",
    email: "/images/home/service-icon-email.png",
    phone: "/images/home/service-icon-phone.png",
    geocode: "/images/home/service-icon-geocode.png",
  },
  australiaFlag: "/icons/australiaFlag.svg",
  nzFlag: "/icons/nzFlag.svg",
  internationalFlag: "/icons/internationalFlag.svg",
  footerLargeLogo: "/seltaris-full-logo.svg",
  footerSocial: {
    facebook: "/icons/fb-logo.svg",
    youtube: "/icons/youtube-logo.svg",
    x: "/icons/x-logo.svg",
    linkedin: "/icons/linkedIn-logo.svg",
    trust: "/icons/lock-logo.svg",
  },
  dataProtectionPage: {
    logo: "/images/data-protection/logo.png",
    heroBanner: "/images/data-protection/hero-banner.png",
    bulletproofIcon: "/images/data-protection/bulletproof-icon.png",
    encryptedCloud: "/images/data-protection/encrypted-cloud.png",
    privateKeys: "/images/data-protection/private-keys.png",
    stepBefore: "/images/data-protection/step-before.png",
    stepClient: "/images/data-protection/step-client.png",
    stepUpload: "/images/data-protection/step-upload.png",
    stepRepository: "/images/data-protection/step-repository.png",
    stepSplits: "/images/data-protection/step-splits.png",
    stepProcessing: "/images/data-protection/step-processing.png",
    stepKeys: "/images/data-protection/step-keys.png",
    stepDelivery: "/images/data-protection/step-delivery.png",
    featureHumanTouch: "/images/human-touch/feature-human-touch.png",
    featureAltraservice: "/images/human-touch/feature-altraservice.png",
    featureDataProtection: "/images/human-touch/feature-data-protection.png",
    featureDesign: "/images/human-touch/feature-design.png",
    featureHealthCheck: "/images/human-touch/feature-health-check.png",
  },
  altraservicePage: {
    heroMockup: "/images/altraservice/hero-mockup.png",
    altraserviceLogo: "/images/altraservice/altraservice-logo.png",
    poweredBy: "/images/altraservice/powered-by.png",
    gbgAltraservice: "/images/altraservice/gbg-altraservice.png",
    macbook: "/images/altraservice/macbook.png",
    slideDistributed: "/images/altraservice/slide-distributed.png",
    slideAsync: "/images/altraservice/slide-async.png",
    slideScale: "/images/altraservice/slide-scale.png",
    engine: "/images/altraservice/engine.png",
    featureHumanTouch: "/images/human-touch/feature-human-touch.png",
    featureAltraservice: "/images/human-touch/feature-altraservice.png",
    featureDataProtection: "/images/human-touch/feature-data-protection.png",
    featureDesign: "/images/human-touch/feature-design.png",
    featureHealthCheck: "/images/human-touch/feature-health-check.png",
  },
  seltarisPlusPage: {
    logo: "/images/seltaris-plus/logo.png",
    healthCheckVisual: "/images/seltaris-plus/health-check-visual.png",
    dataProtectionVisual: "/images/seltaris-plus/data-protection-visual.png",
    sharedLicensingVisual: "/images/seltaris-plus/shared-licensing-visual.png",
    volumeDiscountsVisual: "/images/seltaris-plus/volume-discounts-visual.png",
    supportSpecialist: "/images/seltaris-plus/support-specialist.png",
    sharedLicensingIcon: "/images/seltaris-plus/shared-licensing-icon.png",
    volumeDiscountsIcon: "/images/data-protection/bulletproof-icon.png",
  },
  coreFeatures: {
    featureHumanTouch: "/images/human-touch/feature-human-touch.png",
    featureAltraservice: "/images/human-touch/feature-altraservice.png",
    featureDataProtection: "/images/human-touch/feature-data-protection.png",
    featureDesign: "/images/human-touch/feature-design.png",
    featureHealthCheck: "/images/human-touch/feature-health-check.png",
    humanTouchVisual: "/images/core-features/human-touch-visual.png",
    altraserviceVisual: "/images/core-features/altraservice-visual.png",
    dataProtectionVisual: "/images/core-features/data-protection-visual.png",
    designVisual: "/images/core-features/design-visual.png",
    healthCheckVisual: "/images/core-features/health-check-visual.png",
  },
  healthCheckReportPage: {
    logo: "/images/health-check-report/logo.svg",
    heroMockup: "/images/health-check-report/hero-mockup.png",
    overviewPhoto: "/images/health-check-report/overview-photo.png",
    nextStepBuy: "/images/health-check-report/next-step-buy-visual.png",
    nextStepRealtime:
      "/images/health-check-report/next-step-realtime-visual.png",
    nextStepCapture: "/images/health-check-report/next-step-capture-visual.png",
  },
  addressQualityHealthCheckReportPage: {
    logo: "/images/health-check-report/logo.svg",
    heroMockup: "/images/health-check-report/hero-mockup.png",
    humanTouchLogo: "/images/human-touch/human-touch-logo.png",
    altraserviceLogo: "/images/altraservice/altraservice-logo.png",
    dataProtectionLogo: "/images/data-protection/logo.png",
    transformationSummary: "/images/health-check-report/report-summary.png",
    transformationVerified: "/images/health-check-report/report-verified.png",
    transformationChanges: "/images/health-check-report/report-changes.png",
    refinementVerified: "/images/health-check-report/report-verified.png",
    refinementUnverified: "/images/health-check-report/report-summary.png",
    sampleExamples: "/images/health-check-report/report-changes.png",
    dataQualityAddressingIntelligence:
      "/images/address-quality-health-check-report/data-quality-addressing-intelligence.png",
    dataQualityDataSources: "/images/human-touch/optisource-diagram.png",
    performanceComposite:
      "/images/address-quality-health-check-report/performance-composite.png",
    securityPrivateKeysCard:
      "/images/address-quality-health-check-report/security-private-keys-card.png",
    securityEncryptedCloudCard:
      "/images/address-quality-health-check-report/security-encrypted-cloud-card.png",
    securityIso27001Card:
      "/images/address-quality-health-check-report/security-iso27001-card.png",
  },
  designMadeSimplePage: {
    logo: "/images/design-made-simple/logo.png",
    heroMockup: "/images/design-made-simple/hero-mockup.png",
    featureHumanTouch: "/images/human-touch/feature-human-touch.png",
    featureAltraservice: "/images/human-touch/feature-altraservice.png",
    featureDataProtection: "/images/human-touch/feature-data-protection.png",
    featureDesign: "/images/human-touch/feature-design.png",
    featureHealthCheck: "/images/human-touch/feature-health-check.png",
  },
  humanTouchPage: {
    heroMockup: "/images/human-touch/hero-mockup.png",
    humanTouchLogo: "/images/human-touch/human-touch-logo.png",
    coreDiagram: "/images/human-touch/core-diagram.png",
    intuitionBanner: "/images/human-touch/intuition-banner.png",
    poorDataUi: "/images/human-touch/poor-data-ui.png",
    fuzzyLogic: "/images/human-touch/fuzzy-logic.png",
    phoneticMatching: "/images/human-touch/phonetic-matching.png",
    geographicPhoto: "/images/human-touch/geographic-banner.png",
    intelligentUi: "/images/human-touch/intelligent-ui.png",
    borderingLocalities: "/images/human-touch/bordering-localities.png",
    rangeInterpretation: "/images/human-touch/range-interpretation.png",
    contextualLogic: "/images/human-touch/contextual-logic.png",
    detailsBanner: "/images/human-touch/small-differences-banner.png",
    beautyDetailsBanner: "/images/human-touch/beauty-details-banner.png",
    standardisation: "/images/human-touch/standardisation.png",
    fieldCorrections: "/images/human-touch/field-corrections.png",
    optisourceDiagram: "/images/human-touch/optisource-diagram.png",
    premiumCard: "/images/human-touch/premium-card.png",
    altraserviceEngine: "/images/human-touch/altraservice-engine.png",
    featureHumanTouch: "/images/human-touch/feature-human-touch.png",
    featureAltraservice: "/images/human-touch/feature-altraservice.png",
    featureDataProtection: "/images/human-touch/feature-data-protection.png",
    featureDesign: "/images/human-touch/feature-design.png",
    featureHealthCheck: "/images/human-touch/feature-health-check.png",
  },
  featureSlides: [
    "/images/home/feature-slide-1.png",
    "/images/home/feature-slide-2.png",
    "/images/home/feature-slide-3.png",
  ],
} as const;

export function getAsset(key: string): string {
  if (key in assets) {
    const value = assets[key as keyof typeof assets];
    if (typeof value === "string") return value;
  }
  return assets.heroBackground;
}
